apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zoo-pv-claim
  namespace: kafka-cluster
  labels:
    name: zookeeper-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment-1
  namespace: kafka-cluster
spec:
  serviceName: zoo1
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-1
  template:
    metadata:
      labels:
        name: zookeeper-1 
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        volumeMounts:
          - name: zoo-volume
            mountPath: "/var/lib/zookeeper"
      volumes:
          - name: zoo-volume
            persistentVolumeClaim:
              claimName: zoo-pv-claim