apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  namespace: kafka-cluster
  labels:
    name: kafka-broker-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment-1
  namespace: kafka-cluster
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker-1
  template:
    metadata:
      labels:
        name: kafka-broker-1
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "EXTERNAL_IP"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:3:2:compact"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
        volumeMounts:
          - name: xr-volume
            mountPath: "/kafka/kafka-logs"
      volumes:
          - name: xr-volume
            persistentVolumeClaim:
              claimName: kafka-pv-claim