kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-ui
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-ui
  template:
    metadata:
      labels:
        name: kafka-ui
    spec:        
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: local
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: kafka1:9092
          - name: KAFKA_CLUSTERS_0_ZOOKEEPER
            value: zoo1:2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka-cluster
  labels:
    name: kafka-ui
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: kafka-ui
  type: LoadBalancer